baseURL = "https://kidkarolis.github.io/space-router"
locale = "en-US"
title = "Space Router"
description = "A web router with all the essentials."
disableKinds = ["taxonomy", "term"]

[markup]
  [markup.highlight]
    noClasses = false
    tabWidth = 4
